Repository opencypher/front-end, pull requests merged in 2018-10, with the labels that each got.

#39 Fix errors in semantic checking
  expressions/src/main/scala/org/opencypher/v9_0/expressions/ArithmeticExpressions.scala
Labels: 9.0, bug

#36 Double bug-fixes in pattern comprehesion and missing semantic analysis
  ast/src/main/scala/org/opencypher/v9_0/ast/prettifier/ExpressionStringifier.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/ExpressionTest.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/PatternComprehensionTest.scala
  expressions/src/main/scala/org/opencypher/v9_0/expressions/IterableExpressions.scala
  expressions/src/main/scala/org/opencypher/v9_0/expressions/MapProjection.scala
  frontend/src/main/scala/org/opencypher/v9_0/frontend/phases/CompilationPhases.scala
  frontend/src/main/scala/org/opencypher/v9_0/frontend/phases/SemanticAnalysis.scala
  parser/src/main/scala/org/opencypher/v9_0/parser/Expressions.scala
  parser/src/main/scala/org/opencypher/v9_0/parser/Literals.scala
  parser/src/test/scala/org/opencypher/v9_0/parser/MapProjectionTest.scala
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/rewriters/PatternExpressionPatternElementNamer.scala
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/rewriters/desugarMapProjection.scala
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/rewriters/inlineNamedPathsInPatternComprehensions.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/conditions/noUnnamedPatternElementsInPatternComprehensionTest.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/inlineNamedPathsInPatternComprehensionsTest.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/namePatternComprehensionPatternElementsTest.scala
Labels: 9.0, bug

#37 Refactor deprecations and deprecate most list-comprehension-like functions
  frontend/src/main/scala/org/opencypher/v9_0/frontend/phases/CompilationPhases.scala
  frontend/src/main/scala/org/opencypher/v9_0/frontend/phases/PreparatoryRewriting.scala
  frontend/src/main/scala/org/opencypher/v9_0/frontend/phases/SyntaxDeprecationWarnings.scala
  frontend/src/test/scala/org/opencypher/v9_0/frontend/MultipleGraphClauseSemanticCheckingTest.scala
  frontend/src/test/scala/org/opencypher/v9_0/frontend/phases/SyntaxDeprecationWarningsTest.scala
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/Deprecation.scala
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/rewriters/replaceAliasedFunctionInvocations.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/ReplaceAliasedFunctionInvocationsTest.scala
Labels: 9.0, enhancement

#41 Solve bug in semantic checking of list comprehension
  ast/src/main/scala/org/opencypher/v9_0/ast/semantics/SemanticExpressionCheck.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/ListComprehensionTest.scala
Labels: 9.0, bug

#42 Improve error message for illagal variable access in WITH/RETURN
  ast/src/main/scala/org/opencypher/v9_0/ast/Clause.scala
  ast/src/main/scala/org/opencypher/v9_0/ast/semantics/SemanticError.scala
  frontend/src/test/scala/org/opencypher/v9_0/frontend/SemanticAnalysisErrorMessagesTest.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/NormalizeWithAndReturnClausesTest.scala
Labels: 9.0, enhancement

#40 Add anonymizing rewriter...
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/rewriters/anonymizeQuery.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/AnonymizeQueryTest.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/AnonymizerTestBase.scala
  rewriting/src/test/scala/org/opencypher/v9_0/rewriting/DesugarDesugaredMapProjectionTest.scala
Labels: 9.0, enhancement

#43 Increased coverage for the Prettifier.
  ast/src/main/scala/org/opencypher/v9_0/ast/prettifier/ExpressionStringifier.scala
  ast/src/main/scala/org/opencypher/v9_0/ast/prettifier/Prettifier.scala
  frontend/src/test/scala/org/opencypher/v9_0/frontend/ExpressionStringifierIT.scala
  frontend/src/test/scala/org/opencypher/v9_0/frontend/PrettifierIT.scala
Labels: 9.0

#44 Update comparison semantic checking
  ast/src/main/scala/org/opencypher/v9_0/ast/semantics/SemanticExpressionCheck.scala
  ast/src/main/scala/org/opencypher/v9_0/ast/semantics/SemanticState.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/EqualsTest.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/GreaterThanOrEqualTest.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/GreaterThanTest.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/InfixExpressionTestBase.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/LessThanOrEqualTest.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/LessThanTest.scala
  ast/src/test/scala/org/opencypher/v9_0/ast/semantics/NotEqualsTest.scala
Labels: 9.0

#45 Include index failure message in cypher FailedIndexException
  util/src/main/scala/org/opencypher/v9_0/util/CypherException.scala
  util/src/main/scala/org/opencypher/v9_0/util/spi/MapToPublicExceptions.scala
Labels: 9.0

#46 Fix list comprehension bug with mix of AND and NOT
  frontend/src/test/scala/org/opencypher/v9_0/frontend/phases/rewriting/mergeInPredicatesTest.scala
  rewriting/src/main/scala/org/opencypher/v9_0/rewriting/rewriters/mergeInPredicates.scala
Labels: 9.0, bug
